package KieRule;
import vg.model.*;



rule "Set Lethal force limits"

when
	$limiter : ResponseLimiters(lethalForceMinimum == null)
	Double($minimum : doubleValue) from accumulate(
	PastIncident(responseUsed == PoliceResponseType.LETHAL_FORCE , $m : escalation),
	min($m)
	)
then
	modify($limiter){setLethalForceMinimum($minimum)};
end;

rule "Response worked"

when
	$incidentObject : Incident(responseWorked == true, $pf:allreadyUsedPoliceResponse);
then
	modify($incidentObject){setResponse($pf)};
end;

rule "Threat for life safety"

when
	$incidentObject : Incident(suspectThreatIntention == true && (weapon== WeaponType.SHARP || weapon==WeaponType.FIREARM) && responseWorked == false);
then
	modify($incidentObject){setSuspectThreatForLife(true)};
end;

rule "Lethal force MUST"

when
	$incidentObject : Incident(suspectThreatForLife == true);
then
	modify($incidentObject){setResponse(PoliceResponseType.LETHAL_FORCE)};
end;

rule "Does not cooperate"

when 
	$incidentObject : Incident(allreadyUsedPoliceResponse == PoliceResponseType.VERBALIZATION && responseWorked == false);
then 
	modify($incidentObject){setCooperates(false)};
end;

rule "Threat for safety"

when
	$incidentObject : Incident( cooperates == false && suspectThreatIntention == true);
then 
	modify($incidentObject){setSuspectThreatForSafety(true)};
end;

rule "Less leathal MUST"

when
	$incidentObject : Incident(suspectThreatForSafety == true  && (weapon ==  WeaponType.BLUNT || weapon == WeaponType.NONE));
then
	modify($incidentObject){setResponse(PoliceResponseType.LESS_LETHAL_METHODS)};
end;

rule "Calculate escalation"

when 
	$incidentObject : Incident(response==null);
then
	modify($incidentObject){setEscalation(
	3*$incidentObject.getCriminals()*$incidentObject.getWeapon().coef/$incidentObject.getCops() + $incidentObject.getAllreadyUsedPoliceResponse().limit)};

end;

rule "Calculate escalation to Verbalization"
when 
	$incidentObject : Incident(escalation != null && escalation>=PoliceResponseType.PRESENCE.limit && escalation<PoliceResponseType.VERBALIZATION.limit);
then
	modify($incidentObject){setResponse(PoliceResponseType.VERBALIZATION)};

end;

rule "Calculate escalation to Empty Hand Control"
when 
	$incidentObject : Incident(escalation != null && escalation>=PoliceResponseType.VERBALIZATION.limit && escalation<PoliceResponseType.EMPTY_HAND_CONTROL.limit);
then
	modify($incidentObject){setResponse(PoliceResponseType.EMPTY_HAND_CONTROL)};

end;

rule "Calculate escalation to Less Lethal Methods"
when 
	$incidentObject : Incident(escalation != null && escalation>=PoliceResponseType.EMPTY_HAND_CONTROL.limit && escalation<PoliceResponseType.LESS_LETHAL_METHODS.limit);
then
	modify($incidentObject){setResponse(PoliceResponseType.LESS_LETHAL_METHODS)};

end;

rule "Calculate escalation to Lethal Force"
when 
	$incidentObject : Incident(escalation != null && escalation>=PoliceResponseType.LESS_LETHAL_METHODS.limit);
then
	modify($incidentObject){setResponse(PoliceResponseType.LETHAL_FORCE)};

end;



